import os
import asyncio
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dotenv import load_dotenv

async def run_migration():
    load_dotenv()

    supabase_url = os.environ.get("SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_PUBLISHABLE_DEFAULT_KEY")

    if not supabase_url or not supabase_key:
        print("Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_PUBLISHABLE_DEFAULT_KEY) must be set in .env")
        return

    from supabase import create_async_client
    client = await create_async_client(supabase_url, supabase_key)

    print("Creating game_quest table...")

    try:
        # Check if table exists by trying to select from it
        res = await client.table('game_quest').select('id').limit(1).execute()
        print("Table 'game_quest' exists.")
    except Exception as e:
        print(f"Table 'game_quest' might not exist or error occurred: {e}")
        print("If table does not exist, please run the following SQL in Supabase SQL Editor:")
        print('''
CREATE TABLE public.game_quest (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  scene_list jsonb null,
  quest_entities jsonb null,
  constraint game_quest_pkey primary key (id)
) TABLESPACE pg_default;
''')

if __name__ == "__main__":
    asyncio.run(run_migration())
